version: "3.7"
services:
    api-db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        ports:
            - "33061:3306"
        volumes:
            - api-db:/var/lib/mysql
    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        ports:
            - "8080:80"
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
        volumes:
            - ./api:/app
        depends_on:
            - api-db

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
        volumes:
            - ./api:/app
        depends_on:
            - api-db

volumes:
  api-db:
